Linter:
  Include:
    - 'spec/fixtures/**/*.rb'
Rules:
  Uppercase:
    Enabled: true
  MiddleSpace:
    Enabled: true
  ForwardSlash:
    Enabled: true
  MiddleDash:
    Enabled: true
  EnvironmentVariable:
    Enabled: true
  ClassName:
    Enabled: true
  Constant:
    Enabled: true
  Logger:
    Enabled: true
  Puts:
    Enabled: true
  Query:
    Enabled: true
