Linter:
  Include:
    - 'spec/fixtures/**/*.rb'
Rules:
  ClassName:
    Enabled: true
  Constant:
    Enabled: true
  EnvironmentVariable:
    Enabled: true
  HttpHeaders:
    Enabled: true
  Logger:
    Enabled: true
  MiddleSpace:
    Enabled: true
  Puts:
    Enabled: true
  Scope:
    Enabled: true
  Strftime:
    Enabled: true
  Uppercase:
    Enabled: true
  Words:
    Enabled: true
