AllCops:
  Include:
    - 'lib/**/*.rb'
  Exclude:
    - 'spec/deprecated/**/*.rb'
    - 'config/**/*'
    - 'exe/**/*'
    - 'Gemfiles/**/*'

Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 15
  Exclude:
    - lib/i18n_linter/linter.rb

Metrics/MethodLength:
  CountComments: false
  Max: 24

Metrics/LineLength:
  Max: 100

Style/SymbolArray:
  Enabled: true

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
