version: 2
jobs:
  'ruby-2.3.8':
    environment:
      CC_TEST_REPORTER_ID: da3874f0744dab9c65054068244203daec995477844deb54ce9480047287dc09
    docker:
      - image: circleci/ruby:2.3.8-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfiles/Gemfile.2.3.8.lock" }}
      - run:
          name: install dependencies
          command: |
            BUNDLE_GEMFILE=Gemfiles/Gemfile.2.3.8 bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "Gemfiles/Gemfile.2.3.8.lock" }}
      - run:
          name: run tests
          command: BUNDLE_GEMFILE=Gemfiles/Gemfile.2.3.8 bundle exec rspec
  'ruby-2.4.5':
    environment:
      CC_TEST_REPORTER_ID: da3874f0744dab9c65054068244203daec995477844deb54ce9480047287dc09
    docker:
      - image: circleci/ruby:2.4.5-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfiles/Gemfile.2.4.5.lock" }}
      - run:
          name: install dependencies
          command: |
            BUNDLE_GEMFILE=Gemfiles/Gemfile.2.4.5 bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "Gemfiles/Gemfile.2.4.5.lock" }}
      - run:
          name: run tests
          command: BUNDLE_GEMFILE=Gemfiles/Gemfile.2.4.5 bundle exec rspec
  'ruby-2.5.3':
    environment:
      CC_TEST_REPORTER_ID: da3874f0744dab9c65054068244203daec995477844deb54ce9480047287dc09
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfiles/Gemfile.2.5.3.lock" }}
      - run:
          name: install dependencies
          command: |
            BUNDLE_GEMFILE=Gemfiles/Gemfile.2.5.3 bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "Gemfiles/Gemfile.2.5.3.lock" }}
      - run:
          name: run tests
          command: BUNDLE_GEMFILE=Gemfiles/Gemfile.2.5.3 bundle exec rspec
      - run:
          name: run rubocop
          command: BUNDLE_GEMFILE=Gemfiles/Gemfile.2.5.3 bundle exec rubocop -c .rubocop.yml
      - run:
          name: run reek
          command: BUNDLE_GEMFILE=Gemfiles/Gemfile.2.5.3 bundle exec reek -c config.reek lib
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
            ./cc-test-reporter after-build
workflows:
  version: 2
  build:
    jobs:
      - 'ruby-2.3.8'
      - 'ruby-2.4.5'
      - 'ruby-2.5.3'
