Linter:
  Include:
    - '**/*.rb'
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'
    - 'db/**/*'
Rules:
  ClassName:
    Enabled: true
  Constant:
    Enabled: true
  EnvironmentVariable:
    Enabled: true
  HttpHeaders:
    Enabled: true
  Logger:
    Enabled: true
  MiddleSpace:
    Enabled: true
  MimeType:
    Enabled: true
  Puts:
    Enabled: true
  Query:
    Enabled: true
  RegExp:
    Enabled: true
  Scope:
    Enabled: true
  Strftime:
    Enabled: true
  Underscore:
    Enabled: true
  Words:
    Enabled: true
